seed: 42
use_wandb: false
input_data_dir: ../datasets/external/ai_mix_for_ranking

model:
  backbone_path: microsoft/deberta-v3-large
  max_length: 1024 # 1024
  dropout_rate: 0.05
  gradient_checkpointing: true

train_params:
  per_device_train_batch_size: 32 # 512 # 512
  per_device_eval_batch_size: 32
  num_train_epochs: 2 # 16
  gradient_accumulation_steps: 1

  warmup_pct: 0.1
  eval_frequency: 100 # 500 # 300 # 600
  patience: 10
  save_trigger: 0.0

optimizer:
  head_lr: 2e-5
  lr: 2e-5
  weight_decay: 1e-3
  max_grad_norm: 1.0

  eps: 1e-8
  beta1: 0.9
  beta2: 0.999

  use_bnb: true
  use_llrd: true
  llrd: 0.9

outputs:
  model_dir: ../models/r_ranking

wandb:
  project: detect-ai-a1
  run_name: exp002-r-embed
  tags:
    - deberta